FROM node:latest
WORKDIR /webapp
COPY . .
RUN npm install
EXPOSE 4200
#RUN npm run start
CMD ["npm", "run", "start"]

#RUN chmod a+x script.sh

#CMD ./script.sh

 #docker build -t web:2 .
 #docker container run -p 4200:4200 -it web:2



